In [1]:
import pickle
import pandas as pd

In [2]:
with open('datasets/dict_cathub_dpp_mean_min_max_sum.pickle', 'rb') as f:
    loaded_list_rinfo = pickle.load(f)

In [3]:
len(loaded_list_rinfo)

43678

In [6]:
for agg_func in ['min']:
    for item in loaded_list_rinfo:
        item['ads_embs'] = [float(x) for x in item[agg_func + '_ads_embs']]
    # Convert list of dictionaries to DataFrame
    df = pd.DataFrame(loaded_list_rinfo)
    # Split 'ads_embs' into separate columns
    ads_embs_cols = df['ads_embs'].apply(pd.Series)
    ads_embs_cols.columns = ['e' + str(i) for i in range(256)]
    # Drop the original 'ads_embs' column and concatenate the new columns
    df = df.drop('ads_embs', axis=1)
    df = pd.concat([df, ads_embs_cols], axis=1)
    ## keep the stable reaction
    df = df.sort_values(by='nre')
    df = df.groupby(['sc', 'facet', 'pkey']).first().reset_index()
    ##
    df = df[['sc', 'facet', 'pkey'] + ['e' + str(i) for i in range(256)] + ['nre']]

In [8]:
df.head()

,sc,facet,pkey,e0,e1,e2,e3,e4,e5,e6,...,e247,e248,e249,e250,e251,e252,e253,e254,e255,nre
0,Ag,111,C,-0.899394,-1.535197,-1.460362,-2.442465,-1.987095,-2.080118,-1.140724,...,-1.708042,-1.953401,-1.759886,-0.306596,-2.672878,-1.654552,-0.350089,-1.344883,-2.084778,5.608979
1,Ag,111,CH,-1.247181,-1.497374,-1.511144,-2.442496,-1.860669,-2.095703,-1.216551,...,-1.800487,-2.120257,-1.753915,-1.107516,-2.651525,-1.652508,-1.665542,-1.211603,-2.103264,3.996914
2,Ag,111,CH3,-1.382207,-1.480861,-1.474836,-2.442611,-1.577215,-2.103209,-2.110292,...,-2.004129,-2.371037,-2.268000,-1.189607,-2.636370,-1.785375,-2.173998,-1.833428,-2.114749,1.476339
3,Ag,111,H,-0.978316,-1.468138,-1.446270,-2.442429,-1.758401,-2.118128,-0.362088,...,-1.517575,-1.941850,-1.794821,0.654313,-2.429474,-1.085890,-1.598700,-1.172899,-2.084233,0.338155
4,Ag,111,H2O,-1.731013,-1.953244,-1.516890,-2.442559,-2.114468,-2.172961,-1.411174,...,-2.291821,-1.998838,-1.977141,-0.966124,-2.624609,-1.880830,-1.489448,-1.729870,-2.388728,-0.120299

In [5]:
agg_funcs = ['min', 'mean', 'max', 'sum', 'combined']
for agg_func in agg_funcs:
    # Load dataframe
    df = pd.read_pickle(f'datasets/df_cathub_dpp_{agg_func}.pickle')
    print(agg_func, df.shape)

min (10938, 257)
mean (10938, 257)
max (10938, 257)
sum (10938, 257)
combined (10938, 1025)